### ISSUE TITLE
Error when npm install

### ISSUE THREAD

**Issue by DCMMC** [mohuishou/cet#3]
When I `npm install` in ling-cet-decoder I get two WARN. 
> \# npm install
~~~
npm WARN lifecycle ling-cet-decoder@1.0.3~install: cannot run in wd %s %s (wd=%s) ling-cet-decoder@1.0.3 node-gyp rebuild /home/wwwroot/default/webapp/cet/ling-cet-decoder
npm WARN ling-cet-decoder@1.0.3 No license field.
~~~

Then I `node index.js` in `../` I get this ERROR: 
~~~
module.js:472
    throw err;
    ^

Error: Cannot find module './build/Release/cetdecoder-main'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/wwwroot/default/webapp/cet/ling-cet-decoder/index.js:5:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
~~~

I just used node at first time, can you tell me how can I solve this problem. Thanks.

**Comment by mohuishou** [comment]
You need to tell me your operating system, node version and gcc version

**Comment by mohuishou** [comment]
The test environment is:
os: linux
node: >4.0.0
gcc: >4.8

**Comment by mohuishou** [comment]
Sorry to reply to you so late

**Comment by DCMMC** [comment]
Thank you for reply. I resolved the problem. My OS is `CentOS 6.8`,  node -v is `V7.10.0` , and gcc version is `gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)`.

**Comment by mohuishou** [comment]
So it may be gcc version of the problem

**Comment by XBisATrouble** [comment]
centos6.5 node8.2.1 gcc5.3.1 碰到了一样的报错
